### ISSUE TITLE
release compile

### ISSUE THREAD

**Issue by aFakeCmd** [dashr9230/SA-MP#32]
When compiling in release mode, the game does not load

**Comment by dashr9230** [comment]
By saying "game does not load", I assume is the mod only starts the singleplayer instead, without crash message.

- If you get a white screen during the loading screen and crash afterwards, mostly means that you are using the latest samp.saa file which is not yet compatible with this.
- If the mod just simply start singleplayer without crash, that could mean, that you are using the wrong version of the bass.dll,
or
- The mod got confused with paths, so I highly recommend to use the 0.3.7 server browser (samp.exe) or the debug launcher (samp_debug.exe)

Be aware that this mod is still in progress, so it could have more issues, and I would be thankful if you report those bugs here.

**Comment by aFakeCmd** [comment]
when using debug everything is good

**Comment by dashr9230** [comment]
Can you upload your SA-MP here, or somewhere like Google Drive, OneDrive, or Solidfiles?
Maybe on Discord? You can find me there as RD42#6368

**Comment by aFakeCmd** [comment]
okay

**Comment by dashr9230** [comment]
Issue has been solved by installing Visual C++ Redistributable (2005/2019) and DirectX 9.0c.
