### ISSUE TITLE
Cannot compile IsCandidateActive?

### ISSUE THREAD

**Issue by cutani** [dashr9230/SA-MP#46]
I've installed DirectX SDK and stuff but i got this error how to fix this
![image](https://user-images.githubusercontent.com/77156116/128961323-3e218fdc-64de-424a-8718-50d6916cbb9f.png)

**Comment by dashr9230** [comment]
Rename the `CDXUTIMEEditBox::IsCandicateActive()` to `CDXUTIMEEditBox::IsCandidateActive()`
